{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "isConfigCell": true
   },
   "outputs": [],
   "source": [
    "from sagemaker import get_execution_role\n",
    "\n",
    "#Bucket location to save your custom code in tar.gz format.\n",
    "custom_code_upload_location = 's3://jbs-dataset/customcode'\n",
    "\n",
    "#Bucket location where results of model training are saved.\n",
    "model_artifacts_location = 's3://jbs-dataset/artifacts'\n",
    "\n",
    "#IAM execution role that gives SageMaker access to resources in your AWS account.\n",
    "role = get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "import numpy as np\r\n",
      "import os\r\n",
      "import tensorflow as tf\r\n",
      "\r\n",
      "INPUT_TENSOR_NAME = 'inputs'\r\n",
      "\r\n",
      "# Disable MKL to get a better perfomance for this model.\r\n",
      "os.environ['TF_DISABLE_MKL'] = '1'\r\n",
      "os.environ['TF_DISABLE_POOL_ALLOCATOR'] = '1'\r\n",
      "\r\n",
      "\r\n",
      "def estimator_fn(run_config, params):\r\n",
      "    feature_columns = [tf.feature_column.numeric_column(INPUT_TENSOR_NAME, shape=[29])]\r\n",
      "    return tf.estimator.DNNClassifier(feature_columns=feature_columns,\r\n",
      "                                      hidden_units=[10, 20, 10],\r\n",
      "                                      n_classes=2,\r\n",
      "                                      config=run_config)\r\n",
      "\r\n",
      "\r\n",
      "def serving_input_fn(params):\r\n",
      "    feature_spec = {INPUT_TENSOR_NAME: tf.FixedLenFeature(dtype=tf.float32, shape=[29])}\r\n",
      "    return tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()\r\n",
      "\r\n",
      "\r\n",
      "def train_input_fn(training_dir, params):\r\n",
      "    \"\"\"Returns input function that would feed the model during training\"\"\"\r\n",
      "    return _generate_input_fn(training_dir, 'train_data.csv')\r\n",
      "\r\n",
      "\r\n",
      "def eval_input_fn(training_dir, params):\r\n",
      "    \"\"\"Returns input function that would feed the model during evaluation\"\"\"\r\n",
      "    return _generate_input_fn(training_dir, 'test_data.csv')\r\n",
      "\r\n",
      "\r\n",
      "def _generate_input_fn(training_dir, training_filename):\r\n",
      "    training_set = tf.contrib.learn.datasets.base.load_csv_without_header(\r\n",
      "        filename=os.path.join(training_dir, training_filename),\r\n",
      "        target_dtype=np.int,\r\n",
      "        features_dtype=np.float32)\r\n",
      "\r\n",
      "    return tf.estimator.inputs.numpy_input_fn(\r\n",
      "        x={INPUT_TENSOR_NAME: np.array(training_set.data)},\r\n",
      "        y=np.array(training_set.target),\r\n",
      "        num_epochs=None,\r\n",
      "        shuffle=True)()\r\n",
      "\r\n"
     ]
    }
   ],
   "source": [
    "!cat \"dnn_classifier.py\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "def estimator(model_path, hyperparameters):\n",
    "    feature_columns = [tf.feature_column.numeric_column(INPUT_TENSOR_NAME, shape=[29])]\n",
    "    return tf.estimator.DNNClassifier(feature_columns=feature_columns,\n",
    "                                      hidden_units=[10, 20, 10],\n",
    "                                      n_classes=2,\n",
    "                                      model_dir=model_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_input_fn(training_dir, hyperparameters):\n",
    "    training_set = tf.contrib.learn.datasets.base.load_csv_without_header(\n",
    "        filename=os.path.join(training_dir, 'train.csv'),\n",
    "        target_dtype=np.int,\n",
    "        features_dtype=np.float32)\n",
    "\n",
    "    return tf.estimator.inputs.numpy_input_fn(\n",
    "        x={INPUT_TENSOR_NAME: np.array(training_set.data)},\n",
    "        y=np.array(training_set.target),\n",
    "        num_epochs=None,\n",
    "        shuffle=True)()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "def serving_input_fn(hyperparameters):\n",
    "    feature_spec = {INPUT_TENSOR_NAME: tf.FixedLenFeature(dtype=tf.float32, shape=[29])}\n",
    "    return tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sagemaker.tensorflow import TensorFlow\n",
    "\n",
    "estimator = TensorFlow(entry_point='dnn_classifier.py',\n",
    "                            role=role,\n",
    "                            framework_version='1.9',\n",
    "                            output_path=model_artifacts_location,\n",
    "                            code_location=custom_code_upload_location,\n",
    "                            train_instance_count=1,\n",
    "                            train_instance_type='ml.c4.xlarge',\n",
    "                            training_steps=1000,\n",
    "                            evaluation_steps=100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-02-16 00:51:42 Starting - Starting the training job...\n",
      "2021-02-16 00:51:44 Starting - Launching requested ML instances......\n",
      "2021-02-16 00:52:50 Starting - Preparing the instances for training......\n",
      "2021-02-16 00:54:11 Downloading - Downloading input data\n",
      "2021-02-16 00:54:11 Training - Downloading the training image...\n",
      "2021-02-16 00:54:26 Training - Training image download completed. Training in progress.\u001b[34m2021-02-16 00:54:26,664 INFO - root - running container entrypoint\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:26,664 INFO - root - starting train task\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:26,670 INFO - container_support.training - Training starting\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tf_container - ----------------------TF_CONFIG--------------------------\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tf_container - {\"environment\": \"cloud\", \"cluster\": {\"master\": [\"algo-1:2222\"]}, \"task\": {\"index\": 0, \"type\": \"master\"}}\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tf_container - ---------------------------------------------------------\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tf_container - creating RunConfig:\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tf_container - {'save_checkpoints_secs': 300}\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tensorflow - TF_CONFIG environment variable: {u'environment': u'cloud', u'cluster': {u'master': [u'algo-1:2222']}, u'task': {u'index': 0, u'type': u'master'}}\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,434 INFO - tf_container - invoking the user-provided estimator_fn\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,435 INFO - tensorflow - Using config: {'_save_checkpoints_secs': 300, '_global_id_in_cluster': 0, '_session_config': None, '_keep_checkpoint_max': 5, '_tf_random_seed': None, '_task_type': u'master', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f038e677850>, '_model_dir': u's3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_master': '', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', '_service': None, '_device_fn': None, '_save_summary_steps': 100, '_num_ps_replicas': 0}\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30,436 INFO - tensorflow - Skip starting Tensorflow server as there is only one node in the cluster.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.458818: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /root//.aws/config and using profilePrefix = 1\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.458849: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /root//.aws/credentials and using profilePrefix = 0\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.458860: I tensorflow/core/platform/s3/aws_logging.cc:54] Setting provider to read credentials from /root//.aws/credentials for credentials file and /root//.aws/config for the config file , for use with profile default\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.458869: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating HttpClient with max connections2 and scheme http\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.458885: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 2\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.458908: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating TaskRole with default ECSCredentialsClient and refresh rate 900000\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459683: I tensorflow/core/platform/s3/aws_logging.cc:54] Unable to open config file /root//.aws/credentials for reading.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459702: I tensorflow/core/platform/s3/aws_logging.cc:54] Failed to reload configuration.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459716: I tensorflow/core/platform/s3/aws_logging.cc:54] Unable to open config file /root//.aws/config for reading.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459726: I tensorflow/core/platform/s3/aws_logging.cc:54] Failed to reload configuration.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459739: I tensorflow/core/platform/s3/aws_logging.cc:54] Credentials have expired or will expire, attempting to repull from ECS IAM Service.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459897: I tensorflow/core/platform/s3/aws_logging.cc:54] Pool grown by 2\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.459924: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.465052: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 25\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.467980: I tensorflow/core/platform/s3/aws_logging.cc:54] Pool grown by 2\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.468003: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.519912: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.519951: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:30.521700: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:32,679 WARNING - tensorflow - From /opt/ml/code/iris_dnn_classifier.py:39: load_csv_without_header (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mUse tf.data instead.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35,430 INFO - tensorflow - Calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35,774 INFO - tensorflow - Done calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35,774 INFO - tensorflow - Create CheckpointSaverHook.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.774884: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.784210: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.784241: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.784406: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.802775: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.810200: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.810228: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.810386: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.820894: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.832492: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.832520: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.832653: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.842676: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.850564: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.850598: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.850747: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.863842: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.870273: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.886735: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054351613436875868\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.886961: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.905183: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054351613436875886\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.905404: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.919100: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054351613436875905\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.953515: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.968687: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.980981: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:35.994271: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.029865: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.040989: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36,172 INFO - tensorflow - Graph was finalized.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.177750: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.188921: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.188959: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.189104: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36,315 INFO - tensorflow - Running local_init_op.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36,318 INFO - tensorflow - Done running local_init_op.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.367836: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.375102: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.375141: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.375297: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.505329: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.582427: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054361613436876504\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.585587: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.602030: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.701192: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36,780 INFO - tensorflow - Saving checkpoints for 0 into s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.797852: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.814581: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054361613436876797\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.820267: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.845119: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054361613436876814\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.845416: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.865749: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.901423: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.923019: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.947495: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054361613436876922\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.947739: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:36.970275: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.016387: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.044733: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.064280: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054371613436877044\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.064472: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.075799: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.089484: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.100794: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.113715: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.127146: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.145053: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.179958: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.198931: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.233192: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054371613436877198\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.233439: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.247658: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.262908: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.282406: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.304177: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054371613436877282\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.304408: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.321954: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.357317: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.396734: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.404492: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.404526: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.404675: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.429712: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.481782: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054371613436877429\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.482028: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.501511: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.546568: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.572405: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.583772: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.596854: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.605644: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.616965: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.631010: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.657885: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.670948: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.683459: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:37.691684: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:38,459 INFO - tensorflow - Calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:38,930 WARNING - tensorflow - Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to \"careful_interpolation\" instead.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:38,954 WARNING - tensorflow - Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to \"careful_interpolation\" instead.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:38,976 INFO - tensorflow - Done calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:38,995 INFO - tensorflow - Starting evaluation at 2021-02-16-00:54:38\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,166 INFO - tensorflow - Graph was finalized.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,166 INFO - tensorflow - Restoring parameters from s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt-0\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.181418: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.207479: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.216231: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.227305: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.239340: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.252533: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.263355: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.277146: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.293354: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.306834: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.318304: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,347 INFO - tensorflow - Running local_init_op.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,364 INFO - tensorflow - Done running local_init_op.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,660 INFO - tensorflow - Evaluation [10/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,684 INFO - tensorflow - Evaluation [20/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,707 INFO - tensorflow - Evaluation [30/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,731 INFO - tensorflow - Evaluation [40/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,755 INFO - tensorflow - Evaluation [50/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,785 INFO - tensorflow - Evaluation [60/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,808 INFO - tensorflow - Evaluation [70/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,832 INFO - tensorflow - Evaluation [80/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,855 INFO - tensorflow - Evaluation [90/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,879 INFO - tensorflow - Evaluation [100/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,953 INFO - tensorflow - Finished evaluation at 2021-02-16-00:54:39\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39,954 INFO - tensorflow - Saving dict for global step 0: accuracy = 0.7015625, accuracy_baseline = 0.9984375, auc = 0.67331374, auc_precision_recall = 0.054451853, average_loss = 0.65293795, global_step = 0, label/mean = 0.0015625, loss = 83.57606, precision = 0.0036572623, prediction/mean = 0.47615087, recall = 0.7\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.954435: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.982032: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.982064: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.982241: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:39.995865: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.005426: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.005464: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.005622: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.018880: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.028914: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.028946: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.029096: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.045056: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.065868: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054401613436880044\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.146192: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.166616: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.180488: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.197396: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.255294: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.277263: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.339717: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.380174: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.404275: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,417 INFO - tensorflow - Saving 'checkpoint_path' summary for global step 0: s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt-0\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.418337: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.484934: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.498556: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.512126: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.589788: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.589842: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.590012: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.603947: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.613277: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.613322: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.613487: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.626463: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.636097: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.636128: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.636267: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.650522: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.668526: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.668562: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.668722: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.682858: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.693125: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.693158: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.693330: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.707985: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.714840: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.714867: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.715021: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.730267: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.751868: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054401613436880730\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.752069: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.771380: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054401613436880751\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.771600: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.788929: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054401613436880771\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,797 INFO - tensorflow - Calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,891 INFO - tensorflow - Done calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,896 INFO - tensorflow - Signatures INCLUDED in export for Eval: None\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,896 INFO - tensorflow - Signatures INCLUDED in export for Classify: ['serving_default', 'classification']\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,896 INFO - tensorflow - Signatures INCLUDED in export for Regress: ['regression']\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,897 INFO - tensorflow - Signatures INCLUDED in export for Predict: ['predict']\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,897 INFO - tensorflow - Signatures INCLUDED in export for Train: None\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40,912 INFO - tensorflow - Restoring parameters from s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt-0\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.916732: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.941669: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.951596: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.961743: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:40.970099: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.000642: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.011730: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.024772: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.040121: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.056383: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.079585: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41,090 INFO - tensorflow - Assets added to graph.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41,090 INFO - tensorflow - No assets to write.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.091144: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.102573: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.102602: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.102766: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.115754: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.125447: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.125480: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.125611: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.138119: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.146445: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.146478: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.146610: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.164627: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.182889: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881164\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.202071: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.222190: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881201\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.223689: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.249401: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881222\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.249627: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.266278: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.311211: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.335941: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.365827: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881335\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.366040: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.383325: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.424196: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.443364: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.463502: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881443\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.463703: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.478817: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.493412: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.503348: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.517325: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.532569: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.549637: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.587717: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.603515: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.626900: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881603\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.627116: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.644132: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.663762: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.713751: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.721600: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.721633: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.721790: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.740878: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.768113: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054411613436881740\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41,768 INFO - tensorflow - SavedModel written to: s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/export/Servo/temp-1613436880/saved_model.pb\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.768557: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.777162: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.777188: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.777362: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.791324: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.810079: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.837475: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.851646: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.921552: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.942419: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.971086: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:41.989479: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.028399: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.049105: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.086923: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.105810: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.115440: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.115474: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.115609: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.134119: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.142754: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.142786: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.142944: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42.159711: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,262 INFO - tensorflow - loss = 83.266716, step = 1\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,514 INFO - tensorflow - global_step/sec: 396.518\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,515 INFO - tensorflow - loss = 0.08156366, step = 101 (0.253 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,715 INFO - tensorflow - global_step/sec: 498.274\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,716 INFO - tensorflow - loss = 1.2058456, step = 201 (0.201 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,932 INFO - tensorflow - global_step/sec: 460.189\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:42,933 INFO - tensorflow - loss = 0.034086037, step = 301 (0.217 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,131 INFO - tensorflow - global_step/sec: 503.011\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,132 INFO - tensorflow - loss = 0.07219091, step = 401 (0.199 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,338 INFO - tensorflow - global_step/sec: 482.102\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,339 INFO - tensorflow - loss = 0.047788903, step = 501 (0.208 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,545 INFO - tensorflow - global_step/sec: 483.267\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,546 INFO - tensorflow - loss = 0.016949773, step = 601 (0.207 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,752 INFO - tensorflow - global_step/sec: 482.849\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,753 INFO - tensorflow - loss = 0.053487208, step = 701 (0.207 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,964 INFO - tensorflow - global_step/sec: 471.712\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:43,965 INFO - tensorflow - loss = 0.0061605703, step = 801 (0.212 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44,165 INFO - tensorflow - global_step/sec: 498.264\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44,166 INFO - tensorflow - loss = 0.08890618, step = 901 (0.201 sec)\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44,354 INFO - tensorflow - Saving checkpoints for 1000 into s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.355674: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.376561: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054441613436884355\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.378102: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.408896: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054441613436884376\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.409104: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.426594: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.461874: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.479298: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.502707: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054441613436884479\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.502886: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.522095: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.575428: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.593535: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.613926: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054441613436884593\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.614161: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.629023: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.644527: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.664341: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.680404: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.694525: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.713801: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.752060: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.771176: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.802820: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054441613436884770\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.803052: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.825235: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.847207: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.865447: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.894168: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054441613436884865\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.894447: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.913772: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:44.977481: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.018932: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.026174: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.026203: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.026358: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.047531: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.080178: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054451613436885047\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.080425: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.097716: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.142678: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45,165 INFO - tensorflow - Skip the current checkpoint eval due to throttle secs (600 secs).\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.166277: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.208979: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.223926: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45,263 INFO - tensorflow - Loss for final step: 0.0470296.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45,264 INFO - tensorflow - Training has already ended. But the last eval is skipped due to eval throttle_secs. Now evaluating the final checkpoint.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.264760: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.279951: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.296272: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.310588: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.326536: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.338403: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.369680: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.381513: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.397433: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:45.406616: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,124 INFO - tensorflow - Calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,586 WARNING - tensorflow - Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to \"careful_interpolation\" instead.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,608 WARNING - tensorflow - Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to \"careful_interpolation\" instead.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,631 INFO - tensorflow - Done calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,648 INFO - tensorflow - Starting evaluation at 2021-02-16-00:54:46\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,734 INFO - tensorflow - Graph was finalized.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,734 INFO - tensorflow - Restoring parameters from s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt-1000\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.749039: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.784919: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.792986: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.803300: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.812370: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.824417: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.837624: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.852060: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.865820: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.878458: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46.890059: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,915 INFO - tensorflow - Running local_init_op.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:46,933 INFO - tensorflow - Done running local_init_op.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,119 INFO - tensorflow - Evaluation [10/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,143 INFO - tensorflow - Evaluation [20/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,168 INFO - tensorflow - Evaluation [30/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,191 INFO - tensorflow - Evaluation [40/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,214 INFO - tensorflow - Evaluation [50/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,238 INFO - tensorflow - Evaluation [60/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,263 INFO - tensorflow - Evaluation [70/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,286 INFO - tensorflow - Evaluation [80/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,310 INFO - tensorflow - Evaluation [90/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,335 INFO - tensorflow - Evaluation [100/100]\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,387 INFO - tensorflow - Finished evaluation at 2021-02-16-00:54:47\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,387 INFO - tensorflow - Saving dict for global step 1000: accuracy = 0.999375, accuracy_baseline = 0.9980469, auc = 0.95945054, auc_precision_recall = 0.839767, average_loss = 0.0027795974, global_step = 1000, label/mean = 0.001953125, loss = 0.35578847, precision = 0.84, prediction/mean = 0.0019729515, recall = 0.84\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.388346: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.436485: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.449722: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,461 INFO - tensorflow - Saving 'checkpoint_path' summary for global step 1000: s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt-1000\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.462528: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.537975: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.550911: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.564409: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.575865: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.575893: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.576051: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.588618: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.598880: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.598912: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.599068: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.613585: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.622180: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.622209: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.622368: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.633127: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.642052: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.642079: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.642231: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.660822: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.679441: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054471613436887660\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,685 INFO - tensorflow - Calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,891 INFO - tensorflow - Done calling model_fn.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,896 INFO - tensorflow - Signatures INCLUDED in export for Eval: None\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,897 INFO - tensorflow - Signatures INCLUDED in export for Classify: ['serving_default', 'classification']\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,897 INFO - tensorflow - Signatures INCLUDED in export for Regress: ['regression']\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,897 INFO - tensorflow - Signatures INCLUDED in export for Predict: ['predict']\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,897 INFO - tensorflow - Signatures INCLUDED in export for Train: None\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47,913 INFO - tensorflow - Restoring parameters from s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/model.ckpt-1000\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.919909: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.948794: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.960610: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.973194: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.983671: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:47.995928: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.007832: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.020054: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.030187: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.042495: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.058731: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48,072 INFO - tensorflow - Assets added to graph.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48,072 INFO - tensorflow - No assets to write.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.072970: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.083776: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.083803: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.083959: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.097527: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.106369: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.106397: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.106535: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.121844: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.130515: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.130542: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.130694: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.148707: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.168005: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888148\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.187125: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.210556: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888186\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.212029: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.252816: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888210\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.253053: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.271686: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.313227: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.329969: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.357515: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888329\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.357719: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.375146: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.418498: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.439675: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.456033: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888439\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.456232: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.467964: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.481512: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.493141: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.509676: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.520211: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.537225: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.578014: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.599686: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.621358: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888599\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.621600: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.641504: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.659320: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.711430: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.720846: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.720879: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.721041: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.742563: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.779666: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20210216T0054481613436888742\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48,779 INFO - tensorflow - SavedModel written to: s3://jbs-dataset/artifacts/sagemaker-tensorflow-2021-02-16-00-51-41-822/checkpoints/export/Servo/temp-1613436887/saved_model.pb\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.780136: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.790379: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.790411: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.790563: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.802294: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.822472: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.856379: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.870998: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.926089: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.939828: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.966633: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:48.985553: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.027386: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.068622: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.106928: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.128415: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.137762: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.137789: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.137944: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.154360: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.163419: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.163446: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.163604: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49.179646: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.\u001b[0m\n",
      "\u001b[34m2021-02-16 00:54:49,342 INFO - tf_container - Downloaded saved model at /opt/ml/model/export/Servo/1613436887/saved_model.pb\u001b[0m\n",
      "\n",
      "2021-02-16 00:54:59 Uploading - Uploading generated training model\n",
      "2021-02-16 00:54:59 Completed - Training job completed\n",
      "Training seconds: 72\n",
      "Billable seconds: 72\n",
      "CPU times: user 1.05 s, sys: 70.3 ms, total: 1.12 s\n",
      "Wall time: 3min 42s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "import boto3\n",
    "\n",
    "# use the region-specific sample data bucket\n",
    "region = boto3.Session().region_name\n",
    "train_data_location = 's3://jbs-dataset'.format(region)\n",
    "\n",
    "estimator.fit(train_data_location)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Deploy the trained Model  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-------------!CPU times: user 331 ms, sys: 17.9 ms, total: 348 ms\n",
      "Wall time: 6min 32s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "predictor = estimator.deploy(initial_instance_count=1,\n",
    "                                       instance_type='ml.m4.xlarge')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###  Invoke the Endpoint to get inferences"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /home/ec2-user/anaconda3/envs/tensorflow_p27/cpu/lib/python2.7/site-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'model_spec': {'name': u'generic_model',\n",
       "  'signature_name': u'serving_default',\n",
       "  'version': {'value': 1613436887L}},\n",
       " 'result': {'classifications': [{'classes': [{'label': u'0',\n",
       "      'score': 0.026686491444706917},\n",
       "     {'label': u'1', 'score': 0.973313570022583}]}]}}"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "predictor.predict([-15.819178720771802,8.7759971528627,-22.8046864614815,11.864868080360699,-9.09236053189517,-2.38689320657655,-16.5603681078199,0.9483485947860579,-6.31065843275059,-13.0888909176936,9.81570317447819,-14.0560611837648,0.777191846436601,-13.7610179615936,-0.353635939812489,-7.9574472262599505,-11.9629542349435,-4.7805077876172,0.652498045264831,0.992278949261366,-2.35063374523783,1.03636187430048,1.13605073696052,-1.0434137405139001,-0.10892334328197999,0.657436778462222,2.1364244708551396,-1.41194537483904,-0.3492313067728856]) #expected label to be 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### (Optional) Delete the Endpoint"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(predictor.endpoint)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker\n",
    "\n",
    "sagemaker.Session().delete_endpoint(predictor.endpoint)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  },
  "notice": "Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.  Licensed under the Apache License, Version 2.0 (the \"License\"). You may not use this file except in compliance with the License. A copy of the License is located at http://aws.amazon.com/apache2.0/ or in the \"license\" file accompanying this file. This file is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
